# default profile
spring:
  profiles:
    include:
      - httpclient
      - oauth
    active: development
    ## Security
  security:
    permit-url: /api-docs/**,/configuration/**,/webjars/**,/health
    filter-skip: /health,/configuration,/webjars
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: <client-id>
#            client-secret: <serect-key>
#            scope:
#              - profile
#              - email
#          naver:
#            client-id: <client-id>
#            client-secret: <serect-key>
#            scope:
#              - profile
#              - email
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:822/login/oauth2/code/naver
#
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
  datasource:
    url: jdbc:mysql://localhost:3306/hot6
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
#  jpa:
#
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql=true:
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 822
  tomcat:
    connection-timeout: 30000
    max-threads: 100
    min-spare-threads: 50
    accept-count: 50
    uri-encoding: UTF-8

## AWS Setting
aws:
  s3:
    key:
      access: AKIATERC7HEQPDZWSRUR
      secret: 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
    client:
      region: ap-northeast-2
    bucket:
      name: hot6
    image:
      url:
#        prefix: https://cdn-####
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      secret-key:
